create extension if not exists pgcrypto;

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text, phone text,
 role text not null default 'customer' check(role in('customer','admin')),
 created_at timestamptz not null default now()
);
create table if not exists public.products(
 id text primary key,name text not null,brand text not null,category text not null,subcategory text,series text,series_no text,condition text,
 price numeric(12,2),status text not null default 'available',badge text,image text,description text,tags jsonb not null default '[]',details jsonb not null default '[]',
 stock_qty integer not null default 0 check(stock_qty>=0),active boolean not null default true,updated_at timestamptz not null default now()
);
create table if not exists public.orders(
 id uuid primary key default gen_random_uuid(),order_no text unique not null,user_id uuid not null references public.profiles(id),
 customer_name text not null,customer_phone text not null,customer_email text not null,shipping_address text not null,shipping_city text not null,shipping_pin text not null,
 total_amount numeric(12,2) not null,currency text not null default 'INR',
 status text not null default 'pending_payment' check(status in('pending_payment','paid','processing','packed','shipped','out_for_delivery','delivered','cancelled','refunded')),
 payment_status text not null default 'pending' check(payment_status in('pending','paid','failed','refunded')),
 razorpay_order_id text,razorpay_payment_id text,tracking_number text,tracking_url text,
 expires_at timestamptz not null default(now()+interval '20 minutes'),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.order_items(
 id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id text not null references public.products(id),
 product_name text not null,unit_price numeric(12,2) not null,quantity integer not null check(quantity>0),line_total numeric(12,2) not null
);
create table if not exists public.order_events(
 id bigint generated by default as identity primary key,order_id uuid not null references public.orders(id) on delete cascade,status text not null,message text,created_at timestamptz not null default now()
);
create index if not exists orders_user_idx on public.orders(user_id,created_at desc);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email)) on conflict(id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.create_pending_order(p_items jsonb,p_name text,p_phone text,p_email text,p_address text,p_city text,p_pin text)
returns table(order_id uuid,order_no text,total_amount numeric) language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_order_id uuid;v_order_no text:='NV-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));v_total numeric(12,2):=0;item jsonb;v_product public.products%rowtype;v_qty integer;
begin
 if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
 if jsonb_array_length(p_items)=0 then raise exception 'EMPTY_CART'; end if;
 for item in select * from jsonb_array_elements(p_items) loop
  v_qty:=greatest(1,(item->>'quantity')::integer);
  select * into v_product from public.products where id=item->>'product_id' and active=true for update;
  if not found then raise exception 'PRODUCT_NOT_FOUND'; end if;
  if v_product.price is null then raise exception 'PRICE_ON_REQUEST'; end if;
  if v_product.status='sold' or v_product.stock_qty<v_qty then raise exception 'OUT_OF_STOCK'; end if;
  v_total:=v_total+(v_product.price*v_qty);
 end loop;
 insert into public.orders(order_no,user_id,customer_name,customer_phone,customer_email,shipping_address,shipping_city,shipping_pin,total_amount)
 values(v_order_no,v_user,p_name,p_phone,p_email,p_address,p_city,p_pin,v_total) returning id into v_order_id;
 for item in select * from jsonb_array_elements(p_items) loop
  v_qty:=greatest(1,(item->>'quantity')::integer);select * into v_product from public.products where id=item->>'product_id' for update;
  insert into public.order_items(order_id,product_id,product_name,unit_price,quantity,line_total) values(v_order_id,v_product.id,v_product.name,v_product.price,v_qty,v_product.price*v_qty);
  update public.products set stock_qty=stock_qty-v_qty,status=case when stock_qty-v_qty<=0 then 'sold' else status end,updated_at=now() where id=v_product.id;
 end loop;
 insert into public.order_events(order_id,status,message) values(v_order_id,'pending_payment','Order created; inventory reserved for payment.');
 return query select v_order_id,v_order_no,v_total;
end $$;

create or replace function public.release_order_inventory(p_order_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare i record;begin for i in select product_id,quantity from public.order_items where order_id=p_order_id loop update public.products set stock_qty=stock_qty+i.quantity,status=case when status='sold' then 'available' else status end,updated_at=now() where id=i.product_id;end loop;end $$;

alter table public.profiles enable row level security;alter table public.products enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.order_events enable row level security;
drop policy if exists profiles_self_select on public.profiles;create policy profiles_self_select on public.profiles for select using(id=auth.uid());
drop policy if exists products_public_read on public.products;create policy products_public_read on public.products for select using(active=true);
drop policy if exists orders_self_read on public.orders;create policy orders_self_read on public.orders for select using(user_id=auth.uid());
drop policy if exists order_items_self_read on public.order_items;create policy order_items_self_read on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
drop policy if exists order_events_self_read on public.order_events;create policy order_events_self_read on public.order_events for select using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));

insert into public.products(id,name,brand,category,subcategory,series,series_no,condition,price,status,badge,image,description,tags,details,stock_qty) values
('hw-lm002','Hot Wheels Premium — Lamborghini LM002','Mattel','Die-Cast','Hot Wheels Premium','Fast & Furious Premium','2/5','Card Mint',1199,'available','FAST & FURIOUS','lamborghini-lm002.jpg','The rugged Lamborghini LM002 from the Fast & Furious Premium line.','["Hot Wheels","Fast & Furious","Lamborghini","Premium","Real Riders"]','["Manufacturer: Mattel","Series: Fast & Furious Premium","Card condition: Mint"]',1),
('hw-240sx','Hot Wheels Premium — Nissan 240SX (S14)','Mattel','Die-Cast','Hot Wheels Premium','Fast & Furious Premium','1/5','Card Mint',1199,'available','JDM ICON','nissan-240sx.jpg','An iconic JDM legend from the Fast & Furious Premium series.','["Hot Wheels","Fast & Furious","Nissan","JDM","Premium"]','["Manufacturer: Mattel","Series: Fast & Furious Premium","Card condition: Mint"]',1),
('hw-roadrunner','Hot Wheels Premium — 1970 Custom Plymouth Roadrunner','Mattel','Die-Cast','Hot Wheels Premium','Fast & Furious Premium','4/5','Card Mint',1199,'available','MUSCLE','plymouth-roadrunner.jpg','A classic 1970 Custom Plymouth Roadrunner from the Fast & Furious Premium series.','["Hot Wheels","Fast & Furious","Plymouth","Muscle Car","Premium"]','["Manufacturer: Mattel","Series: Fast & Furious Premium","Card condition: Mint"]',1),
('fs-targat','Funskool G.I. Joe — T.A.R.G.A.T.','Funskool','Action Figures','Vintage G.I. Joe','International Heroes',null,'Fair — see images',9999,'available','VINTAGE','targat.jpg','T.A.R.G.A.T. — Cobra Trans-Atmospheric Rapid Global Assault Trooper. MOC and never opened.','["G.I. Joe","Funskool","Vintage","MOC","International Heroes"]','["Country of origin: India","Type: MOC — Never Opened","DIT/LIT not covered"]',1),
('fs-budo','Funskool G.I. Joe — Budo Samurai Warrior','Funskool','Action Figures','Vintage G.I. Joe','International Heroes',null,'OK — see images',8999,'available','VINTAGE','budo.jpg','Budo, the Samurai Warrior. MOC and never opened.','["G.I. Joe","Funskool","Budo","Vintage","MOC"]','["Country of origin: India","Type: MOC — Never Opened","DIT/LIT not covered"]',1),
('fs-incinerator','Funskool G.I. Joe — Incinerator','Funskool','Action Figures','Vintage G.I. Joe','International Heroes',null,'Figure excellent; yellow blister',10999,'available','RARE','incinerator.jpg','Incinerator, the Cobra Flamethrower Specialist.','["G.I. Joe","Funskool","Incinerator","Vintage","MOC"]','["Country of origin: India","Type: MOC — Never Opened","No returns; DIT/LIT not covered"]',1),
('fs-scrap-iron','Funskool G.I. Joe — Scrap Iron','Funskool','Action Figures','Vintage G.I. Joe','International Heroes',null,'Blister cracked and yellow',null,'available','PRICE ON REQUEST','scrap-iron.jpg','Scrap Iron, a Cobra anti-tank specialist.','["G.I. Joe","Funskool","Scrap Iron","Vintage","MOC"]','["Country of origin: India","Type: MOC — Never Opened","Price: On request"]',0),
('fs-tripwire','Funskool G.I. Joe — Tripwire','Funskool','Action Figures','Vintage G.I. Joe','International Heroes',null,'Fair — see images',8999,'sold','SOLD OUT','tripwire.jpg','Tripwire, a Bomb Squad specialist. This listing has been sold.','["G.I. Joe","Funskool","Tripwire","Vintage","Sold Out"]','["Country of origin: India","Type: MOC — Never Opened","Status: Sold out"]',0)
on conflict(id) do update set name=excluded.name,brand=excluded.brand,category=excluded.category,price=excluded.price,badge=excluded.badge,image=excluded.image,description=excluded.description,tags=excluded.tags,details=excluded.details,updated_at=now();