(async function(){
const gate=document.getElementById('adminGate'),panel=document.getElementById('adminPanel'),msg=document.getElementById('adminMsg');
document.getElementById('adminGoogle').onclick=()=>NV_AUTH.google('admin.html');document.getElementById('adminSignOut').onclick=()=>NV_AUTH.signOut();
if(!NV_AUTH.configured){msg.textContent='Setup required: add Supabase credentials in config.js.';return;}const {data:{session},error:sessionError}=await NV_AUTH.client.auth.getSession();if(sessionError){msg.textContent='Session error: '+sessionError.message;return;}if(!session?.user){msg.textContent='Sign in with your administrator Google account.';return;}
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('ordersTab').hidden=b.dataset.tab!=='orders';document.getElementById('inventoryTab').hidden=b.dataset.tab!=='inventory';document.getElementById('bulkTab').hidden=b.dataset.tab!=='bulk';document.getElementById('valuationTab').hidden=b.dataset.tab!=='valuation';});
async function api(action,body={}){const {data:{session}}=await NV_AUTH.client.auth.getSession();const r=await fetch(`${NV_CONFIG.supabaseUrl}/functions/v1/admin-api`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...body})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Admin request failed');return j;}
const imageByName={'funskool g i joe budo samurai warrior':'budo.jpg','funskool g i joe incinerator':'incinerator.jpg','funskool g i joe scrap iron':'scrap-iron.jpg','funskool g i joe t a r g a t':'targat.jpg','funskool g i joe tripwire':'tripwire.jpg','hot wheels premium 1970 custom plymouth roadrunner':'plymouth-roadrunner.jpg','hot wheels premium lamborghini lm002':'lamborghini-lm002.jpg','hot wheels premium nissan 240sx s14':'nissan-240sx.jpg'};
const normalizeName=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim();
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const addForm=document.getElementById('addProductForm');document.getElementById('showAddProduct').onclick=()=>{addForm.hidden=false;addForm.querySelector('[name=name]').focus()};document.getElementById('cancelAddProduct').onclick=()=>{addForm.hidden=true};addForm.onsubmit=async e=>{e.preventDefault();const m=document.getElementById('addProductMessage');const button=addForm.querySelector('[type=submit]');button.disabled=true;m.textContent='Saving…';try{const v=Object.fromEntries(new FormData(addForm));await api('create_product',{product:{name:v.name,brand:v.brand,price:Number(v.price),cost_price:v.cost_price===''?null:Number(v.cost_price),stock:Number(v.stock),category_id:v.category_id,sku:v.sku,condition:v.condition,description:v.description}});m.textContent='Draft product created.';addForm.reset();await load()}catch(err){m.textContent=err.message}finally{button.disabled=false}};
const inventoryMessage=document.getElementById('inventoryMessage');
function suggestBrand(name,description){const text=(String(name||'')+' '+String(description||'')).toLowerCase();const checks=[[/hot wheels/,'Hot Wheels'],[/mini[ -]?gt/,'Mini GT'],[/tomica/,'Tomica'],[/g[. ]*i[. ]*joe|cobra|international heroes/,'G.I. Joe'],[/masters of the universe|motu|he-man|skeletor/,'Masters of the Universe'],[/transformers|optimus|megatron/,'Transformers'],[/star wars|mandalorian/,'Star Wars'],[/matchbox/,'Matchbox'],[/majorette/,'Majorette'],[/lego/,'LEGO'],[/marvel|spider-man|avengers/,'Marvel'],[/batman|superman|dc comics/,'DC'],[/funskool/,'Funskool'],[/hasbro/,'Hasbro'],[/mattel/,'Mattel']];return checks.find(([re])=>re.test(text))?.[1]||''}
function wireBrandSuggestion(form){const name=form.elements.namedItem('name'),brand=form.elements.namedItem('brand'),description=form.elements.namedItem('description');let lastSuggested='';function check(){const suggestion=suggestBrand(name.value,description.value);if(suggestion&&(!brand.value.trim()||brand.value===lastSuggested)){brand.value=suggestion;lastSuggested=suggestion}}name.addEventListener('input',check);description.addEventListener('input',check);brand.addEventListener('input',()=>{if(brand.value!==lastSuggested)lastSuggested=''});}wireBrandSuggestion(addForm);

const editForm=document.getElementById('editProductForm'),editMessage=document.getElementById('editProductMessage');wireBrandSuggestion(editForm);
let productsCache=[],currentImages=[];
function renderBulkInventory(){const el=document.getElementById('bulkInventory');el.replaceChildren();for(const p of productsCache){const row=document.createElement('label');row.className='inventory-row';const name=document.createElement('span');name.textContent=p.name+' ('+p.status+')';const input=document.createElement('input');input.type='number';input.min='0';input.step='1';input.value=String(p.stock);input.dataset.bulkId=p.id;input.dataset.original=String(p.stock);row.append(name,input);el.append(row)}}
document.getElementById('saveBulkInventory').onclick=async()=>{const m=document.getElementById('bulkMessage'),btn=document.getElementById('saveBulkInventory');const changes=[...document.querySelectorAll('[data-bulk-id]')].filter(x=>x.value!==x.dataset.original).map(x=>({product_id:x.dataset.bulkId,stock:Number(x.value)}));if(!changes.length){m.textContent='No stock changes to save.';return}if(changes.some(x=>!Number.isSafeInteger(x.stock)||x.stock<0)){m.textContent='Enter valid non-negative whole numbers.';return}btn.disabled=true;m.textContent='Saving '+changes.length+' product(s)…';try{const result=await api('bulk_update_inventory',{updates:changes});await load();m.textContent='Updated and verified '+result.updated+' product(s).'}catch(e){m.textContent='Bulk update failed: '+e.message}finally{btn.disabled=false}};
document.getElementById('ensureMerchCategories').onclick=async e=>{const btn=e.currentTarget;btn.disabled=true;const label=btn.textContent;btn.textContent='Setting up…';try{await api('ensure_catalog_categories');await loadCategories();btn.textContent='Categories ready ✓';}catch(err){btn.textContent=label;alert('Category setup failed: '+err.message);}finally{btn.disabled=false;}};
async function loadCategories(){const j=await api('categories');for(const id of ['addCategory','editCategory']){const sel=document.getElementById(id);sel.replaceChildren(new Option('Uncategorized',''));(j.categories||[]).forEach(c=>sel.add(new Option(c.name,c.id)))}}
function showPhotos(){const el=document.getElementById('photoPreview');el.replaceChildren();currentImages.forEach((url,i)=>{const wrap=document.createElement('div'),img=document.createElement('img'),btn=document.createElement('button');img.src=url;img.alt='Photo';img.width=75;btn.type='button';btn.textContent='Remove';btn.onclick=()=>{currentImages.splice(i,1);showPhotos()};wrap.append(img,btn);el.append(wrap)})}
window.editProduct=id=>{const p=productsCache.find(x=>x.id===id);if(!p)return;editForm.hidden=false;addForm.hidden=true;for(const k of ['id','name','brand','price','cost_price','stock','sku','condition','description','category_id','status'])editForm.elements.namedItem(k).value=p[k]??'';currentImages=Array.isArray(p.image_urls)?[...p.image_urls]:[];showPhotos();editMessage.textContent='';editForm.scrollIntoView({behavior:'smooth'})};
document.getElementById('cancelEditProduct').onclick=()=>{editForm.hidden=true};
editForm.onsubmit=async e=>{e.preventDefault();const btn=editForm.querySelector('[type=submit]');btn.disabled=true;try{const p=Object.fromEntries(new FormData(editForm)),files=[...document.getElementById('productPhotos').files];if(currentImages.length+files.length>12)throw Error('Maximum 12 photos');for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw Error('Images must be JPG, PNG or WebP up to 5 MB');editMessage.textContent='Uploading '+file.name;const signed=await api('image_upload_url',{product_id:p.id,filename:file.name.replace(/[^a-z0-9_.-]/gi,'-')});const {error}=await NV_AUTH.client.storage.from('product-media').uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type});if(error)throw error;currentImages.push(signed.url)}await api('update_product',{product_id:p.id,product:{...p,price:Number(p.price),cost_price:p.cost_price===''?null:Number(p.cost_price),stock:Number(p.stock),image_urls:currentImages}});document.getElementById('productPhotos').value='';await load();editForm.hidden=true;inventoryMessage.textContent='Product saved successfully.'}catch(err){editMessage.textContent='Save failed: '+err.message}finally{btn.disabled=false}};
loadCategories().catch(e=>{inventoryMessage.textContent='Categories: '+e.message});


const demoButton=document.createElement('button');demoButton.type='button';demoButton.className='btn ghost';demoButton.textContent='Preview test shipment';demoButton.style.marginBottom='14px';
const demo=document.createElement('div');demo.id='shippingDemo';demo.hidden=true;
const ordersContainer=document.getElementById('adminOrders');ordersContainer.before(demoButton,demo);
demoButton.onclick=()=>{demo.hidden=!demo.hidden;demoButton.textContent=demo.hidden?'Preview test shipment':'Hide test shipment';if(demo.hidden)return;demo.innerHTML='<article class="admin-order" style="border:1px dashed #d8ff3e;padding:18px;margin-bottom:18px"><p class="eyebrow">DEMO ONLY · NOT A REAL ORDER</p><h3>TEST-SHIP-001</h3><p>Sample collectible × 1 · No payment, stock or database changes</p><div class="admin-grid"><label>Status<select id="demoStatus"><option>confirmed</option><option>processing</option><option>packed</option><option>shipped</option><option>delivered</option></select></label><label>Courier<select id="demoCourier"><option value="delhivery">Delhivery</option><option value="india-post">India Post</option><option value="dtdc">DTDC</option><option value="blue-dart">Blue Dart</option></select></label><label>Sample AWB<input id="demoAwb" placeholder="Enter a sample AWB"></label></div><button class="btn primary" type="button" id="demoSave">Preview customer tracking</button><p id="demoResult" role="status"></p></article>';document.getElementById('demoSave').onclick=()=>{const awb=document.getElementById('demoAwb').value.trim(),courier=document.getElementById('demoCourier').value,status=document.getElementById('demoStatus').value;if(!/^[A-Za-z0-9\\-\\/ ]{1,100}$/.test(awb)){document.getElementById('demoResult').textContent='Enter a sample AWB using letters or numbers.';return}const links={'delhivery':'https://www.delhivery.com/tracking','india-post':'https://www.indiapost.gov.in/','dtdc':'https://www.dtdc.in/','blue-dart':'https://www.bluedart.com/'};const result=document.getElementById('demoResult');result.replaceChildren();result.append(document.createTextNode('Customer preview: '+status+' · AWB '+awb+' · '));const a=document.createElement('a');a.href=links[courier];a.target='_blank';a.rel='noopener noreferrer';a.textContent='Track on courier website';result.append(a);result.append(document.createTextNode(' (sample AWB may not resolve)'));};};


function renderValuation(j){
 const products=j.products||[],orders=j.orders||[],fmt=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2}),qty=products.reduce((s,p)=>s+Number(p.stock||0),0),value=products.reduce((s,p)=>s+Number(p.stock||0)*Number(p.price||0),0),paid=orders.filter(o=>o.payment_status==='paid'),revenue=paid.reduce((s,o)=>s+Number(o.total||0),0);
 const known=products.filter(p=>p.cost_price!==null&&p.cost_price!==undefined),investment=known.reduce((s,p)=>s+Number(p.stock||0)*Number(p.cost_price||0),0),potentialMargin=known.reduce((s,p)=>s+Number(p.stock||0)*(Number(p.price||0)-Number(p.cost_price||0)),0);const metrics=[['Known stock investment',fmt(investment)],['Potential gross margin (known costs)',fmt(potentialMargin)],['Missing purchase costs',products.length-known.length],['Stock units',qty],['Listed inventory value',fmt(value)],['Paid order revenue',fmt(revenue)],['Paid orders',paid.length],['Unsold SKUs',products.filter(p=>Number(p.stock)>0).length],['Low / zero stock',products.filter(p=>Number(p.stock)<=Number(p.low_stock_threshold??0)).length]];
 document.getElementById('valuationSummary').innerHTML=metrics.map(([k,v])=>'<div class="stat-card"><span>'+escapeHtml(k)+'</span><strong>'+escapeHtml(v)+'</strong></div>').join('');
 const by=new Map();for(const p of products){const key=p.category_id||'Uncategorized';const x=by.get(key)||{count:0,units:0,value:0};x.count++;x.units+=Number(p.stock||0);x.value+=Number(p.stock||0)*Number(p.price||0);by.set(key,x)}
 document.getElementById('valuationCategories').innerHTML='<div style="overflow-x:auto"><table style="width:100%;text-align:left"><thead><tr><th>Category ID</th><th>Products</th><th>Units</th><th>Listed value</th></tr></thead><tbody>'+[...by].map(([k,x])=>'<tr><td>'+escapeHtml(k)+'</td><td>'+x.count+'</td><td>'+x.units+'</td><td>'+fmt(x.value)+'</td></tr>').join('')+'</tbody></table></div>';
 document.getElementById('valuationProducts').innerHTML='<div style="overflow-x:auto"><table style="width:100%;text-align:left"><thead><tr><th>Product</th><th>SKU</th><th>Status</th><th>Stock</th><th>Price</th><th>Cost / unit</th><th>Stock cost</th><th>Potential margin</th><th>Listed value</th></tr></thead><tbody>'+products.map(p=>'<tr><td>'+escapeHtml(p.name)+'</td><td>'+escapeHtml(p.sku||'—')+'</td><td>'+escapeHtml(p.status)+'</td><td>'+Number(p.stock||0)+'</td><td>'+fmt(p.price)+'</td><td>'+(p.cost_price==null?'Not set':fmt(p.cost_price))+'</td><td>'+(p.cost_price==null?'—':fmt(Number(p.cost_price)*Number(p.stock||0)))+'</td><td>'+(p.cost_price==null?'—':fmt((Number(p.price||0)-Number(p.cost_price))*Number(p.stock||0)))+'</td><td>'+fmt(Number(p.price||0)*Number(p.stock||0))+'</td></tr>').join('')+'</tbody></table></div>';
 document.getElementById('valuationOrders').innerHTML='<p class="micro-note">Based on the latest '+orders.length+' orders loaded; older orders may not be included.</p><div style="overflow-x:auto"><table style="width:100%;text-align:left"><thead><tr><th>Order</th><th>Date</th><th>Status</th><th>Payment</th><th>Total</th></tr></thead><tbody>'+orders.map(o=>'<tr><td>'+escapeHtml(o.order_number)+'</td><td>'+escapeHtml((o.created_at||'').slice(0,10))+'</td><td>'+escapeHtml(o.status)+'</td><td>'+escapeHtml(o.payment_status)+'</td><td>'+fmt(o.total)+'</td></tr>').join('')+'</tbody></table></div>';
}

async function load(){try{const j=await api('dashboard');if(!Array.isArray(j.products))throw Error('Product data missing from admin response');renderValuation(j);document.getElementById('statOrders').textContent=j.stats.orders;document.getElementById('statRevenue').textContent='₹'+Number(j.stats.revenue).toLocaleString('en-IN');document.getElementById('statLow').textContent=j.stats.low_stock;
document.getElementById('adminOrders').innerHTML=j.orders.map(o=>`<article class="admin-order"><div class="order-top"><div><strong>${escapeHtml(o.order_number)}</strong><small>${escapeHtml(o.customer_name)} · ${escapeHtml(o.customer_email||'')}</small></div><span class="status-chip">${escapeHtml(o.status)}</span></div><p>${(o.order_items||[]).map(i=>`${escapeHtml(i.product_name)} × ${Number(i.quantity)}`).join(' · ')}</p><div class="admin-grid"><label>Status<select data-status="${o.id}"><option>pending</option><option>confirmed</option><option>processing</option><option>packed</option><option>shipped</option><option>delivered</option><option>cancelled</option><option>refunded</option></select></label><label>Courier<select data-courier="${o.id}"><option value="">Custom tracking URL</option><option value="delhivery">Delhivery</option><option value="india-post">India Post</option><option value="dtdc">DTDC</option><option value="blue-dart">Blue Dart</option></select></label><label>Tracking number<input data-track="${o.id}" value="${escapeHtml(o.tracking_number||'')}" placeholder="AWB / tracking number"></label><label>Tracking URL<input data-url="${o.id}" value="${escapeHtml(o.tracking_url||'')}" placeholder="https://…"></label></div><button class="btn primary" onclick="updateOrder('${o.id}')">Save order update</button></article>`).join('')||'<p>No orders yet.</p>';
j.orders.forEach(o=>{const c=document.querySelector(`[data-courier="${o.id}"]`);if(c&&o.tracking_url){try{const h=new URL(o.tracking_url).hostname;c.value=h.endsWith('delhivery.com')?'delhivery':h.endsWith('indiapost.gov.in')?'india-post':h.endsWith('dtdc.in')?'dtdc':h.endsWith('bluedart.com')?'blue-dart':''}catch(_){}}const s=document.querySelector(`[data-status="${o.id}"]`);if(s)s.value=o.status});
productsCache=j.products||[];renderBulkInventory();document.getElementById('inventory').innerHTML=j.products.map(p=>`<div class="inventory-row">${(p.image_urls?.[0]||imageByName[normalizeName(p.name)])?`<img src="${escapeHtml(p.image_urls?.[0]||imageByName[normalizeName(p.name)])}" alt="" loading="lazy">`:`<span aria-label="No image" style="display:grid;place-items:center;width:56px;height:56px;background:#222;color:#888;font-size:9px">No image</span>`}<div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.brand)} · ₹${Number(p.price||0).toLocaleString('en-IN')} · ${escapeHtml(p.status)}</small></div><input type="number" min="0" data-stock="${p.id}" value="${p.stock}"><button class="btn ghost" onclick="updateStock('${p.id}')">Update</button><button class="btn ghost" data-edit="${p.id}">Edit</button></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>window.editProduct(b.dataset.edit));
}catch(e){const warning=document.getElementById('inventoryMessage');if(warning)warning.textContent='Inventory loading error: '+e.message;const inventory=document.getElementById('inventory');if(inventory)inventory.textContent='Unable to load products: '+e.message;const summary=document.getElementById('valuationSummary');if(summary)summary.textContent='Report unavailable: '+e.message;return false;}return true;}
window.updateOrder=async id=>{try{const courier=document.querySelector(`[data-courier="${id}"]`).value;const awb=document.querySelector(`[data-track="${id}"]`).value.trim();let link=document.querySelector(`[data-url="${id}"]`).value.trim();const sites={'delhivery':'https://www.delhivery.com/tracking','india-post':'https://www.indiapost.gov.in/','dtdc':'https://www.dtdc.in/','blue-dart':'https://www.bluedart.com/'};if(courier&&awb)link=sites[courier];await api('update_order',{order_id:id,status:document.querySelector(`[data-status="${id}"]`).value,tracking_number:awb,tracking_url:link});await load();alert('Order updated and customer email queued.');}catch(e){alert(e.message)}};
window.updateStock=async id=>{const input=document.querySelector(`[data-stock="${id}"]`),button=input?.closest('.inventory-row')?.querySelector('button');const value=Number(input?.value);if(!Number.isSafeInteger(value)||value<0){inventoryMessage.textContent='Please enter a non-negative whole number.';return;}if(button)button.disabled=true;inventoryMessage.textContent='Saving stock…';try{const result=await api('update_inventory',{product_id:id,stock:value});const fresh=await api('dashboard');const saved=fresh.products?.find(p=>p.id===id);if(!saved)throw new Error('Product missing from fresh inventory');if(Number(saved.stock)!==value)throw new Error('Database still shows '+saved.stock+' unit(s); requested '+value+'. Check that the latest admin-api function was deployed.');await load();inventoryMessage.textContent='Stock saved and verified: '+value+' unit(s).';}catch(e){inventoryMessage.textContent='Stock update failed: '+e.message;}finally{if(button)button.disabled=false}};
gate.hidden=true;panel.hidden=false;await load();
})();