(async function(){
const gate=document.getElementById('adminGate'),panel=document.getElementById('adminPanel'),msg=document.getElementById('adminMsg');
document.getElementById('adminGoogle').onclick=()=>NV_AUTH.google('admin.html');document.getElementById('adminSignOut').onclick=()=>NV_AUTH.signOut();
if(!NV_AUTH.configured){msg.textContent='Setup required: add Supabase credentials in config.js.';return;}const {data:{session},error:sessionError}=await NV_AUTH.client.auth.getSession();if(sessionError){msg.textContent='Session error: '+sessionError.message;return;}if(!session?.user){msg.textContent='Sign in with your administrator Google account.';return;}
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('ordersTab').hidden=b.dataset.tab!=='orders';document.getElementById('inventoryTab').hidden=b.dataset.tab!=='inventory';});
async function api(action,body={}){const {data:{session}}=await NV_AUTH.client.auth.getSession();const r=await fetch(`${NV_CONFIG.supabaseUrl}/functions/v1/admin-api`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...body})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Admin request failed');return j;}
const imageByName={'funskool gi joe budo samurai warrior':'budo.jpg','funskool gi joe incinerator':'incinerator.jpg','funskool gi joe scrap iron':'scrap-iron.jpg','funskool gi joe targat':'targat.jpg','funskool gi joe tripwire':'tripwire.jpg','hot wheels premium 1970 custom plymouth roadrunner':'plymouth-roadrunner.jpg','hot wheels premium lamborghini lm002':'lamborghini-lm002.jpg','hot wheels premium nissan 240sx s14':'nissan-240sx.jpg'};
const normalizeName=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim();
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const addForm=document.getElementById('addProductForm');document.getElementById('showAddProduct').onclick=()=>{addForm.hidden=false;addForm.querySelector('[name=name]').focus()};document.getElementById('cancelAddProduct').onclick=()=>{addForm.hidden=true};addForm.onsubmit=async e=>{e.preventDefault();const m=document.getElementById('addProductMessage');const button=addForm.querySelector('[type=submit]');button.disabled=true;m.textContent='Saving…';try{const v=Object.fromEntries(new FormData(addForm));await api('create_product',{product:{name:v.name,brand:v.brand,price:Number(v.price),stock:Number(v.stock),sku:v.sku,condition:v.condition,description:v.description}});m.textContent='Draft product created.';addForm.reset();await load()}catch(err){m.textContent=err.message}finally{button.disabled=false}};
async function load(){try{const j=await api('dashboard');document.getElementById('statOrders').textContent=j.stats.orders;document.getElementById('statRevenue').textContent='₹'+Number(j.stats.revenue).toLocaleString('en-IN');document.getElementById('statLow').textContent=j.stats.low_stock;
document.getElementById('adminOrders').innerHTML=j.orders.map(o=>`<article class="admin-order"><div class="order-top"><div><strong>${o.order_no}</strong><small>${o.customer_name} · ${o.customer_email||''}</small></div><span class="status-chip">${o.status}</span></div><p>${(o.order_items||[]).map(i=>`${i.product_name} × ${i.quantity}`).join(' · ')}</p><div class="admin-grid"><label>Status<select data-status="${o.id}"><option>pending_payment</option><option>paid</option><option>processing</option><option>packed</option><option>shipped</option><option>out_for_delivery</option><option>delivered</option><option>cancelled</option><option>refunded</option></select></label><label>Tracking number<input data-track="${o.id}" value="${o.tracking_number||''}" placeholder="AWB / tracking number"></label><label>Tracking URL<input data-url="${o.id}" value="${o.tracking_url||''}" placeholder="https://…"></label></div><button class="btn primary" onclick="updateOrder('${o.id}')">Save order update</button></article>`).join('')||'<p>No orders yet.</p>';
j.orders.forEach(o=>{const s=document.querySelector(`[data-status="${o.id}"]`);if(s)s.value=o.status});
document.getElementById('inventory').innerHTML=j.products.map(p=>`<div class="inventory-row">${imageByName[normalizeName(p.name)]?`<img src="${encodeURI(imageByName[normalizeName(p.name)])}" alt="" loading="lazy">`:`<span aria-label="No image" style="display:grid;place-items:center;width:56px;height:56px;background:#222;color:#888;font-size:9px">No image</span>`}<div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.brand)} · ₹${Number(p.price||0).toLocaleString('en-IN')} · ${escapeHtml(p.status)}</small></div><input type="number" min="0" data-stock="${p.id}" value="${p.stock}"><button class="btn ghost" onclick="updateStock('${p.id}')">Update</button></div>`).join('');
}catch(e){msg.textContent=e.message;return false;}return true;}
window.updateOrder=async id=>{try{await api('update_order',{order_id:id,status:document.querySelector(`[data-status="${id}"]`).value,tracking_number:document.querySelector(`[data-track="${id}"]`).value,tracking_url:document.querySelector(`[data-url="${id}"]`).value});await load();alert('Order updated and customer email queued.');}catch(e){alert(e.message)}};
window.updateStock=async id=>{try{await api('update_inventory',{product_id:id,stock:Number(document.querySelector(`[data-stock="${id}"]`).value)});await load();}catch(e){alert(e.message)}};
if(await load()){gate.hidden=true;panel.hidden=false;}
})();