from pathlib import Path
root=Path('/mnt/data/nerdverse-final')

def shell(title, body, active=''):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="NerdVerse India — collector-grade collectibles in India."><title>{title} | NerdVerse India</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"></head><body>
<div class="announcement">FREE SHIPPING ON ORDERS OVER ₹1,999 · COLLECTOR DROPS EVERY WEEK</div><header class="site-header"><a class="logo-link" href="index.html"><img src="assets/nerdverse-logo.png" alt="NerdVerse India"></a><nav><a href="index.html">Home</a><a href="shop.html">Shop</a><a href="categories.html">Categories</a><a href="brands.html">Brands</a><a href="rare.html">Rare Finds</a><a href="about.html">About</a><a href="contact.html">Contact</a></nav><div class="header-actions"><button class="icon-btn" id="searchBtn">⌕</button><button class="cart-btn" id="cartBtn">Cart <span id="cartCount">0</span></button></div></header>
<main>{body}</main><footer><div class="footer-top"><div class="footer-brand"><img src="assets/nerdverse-logo.png" alt="NerdVerse India"></div><p>Built for collectors.<br>Powered by obsession.</p><div class="footer-links"><a href="shop.html">Shop</a><a href="categories.html">Categories</a><a href="brands.html">Brands</a><a href="rare.html">Rare Finds</a><a href="about.html">About</a><a href="contact.html">Contact</a><a href="policies.html">Policies</a><a href="https://www.instagram.com/nerdverseindia/" target="_blank" rel="noopener">Instagram</a></div></div><div class="footer-bottom"><span>© 2026 NerdVerse India</span><span>Made for the hunt.</span></div></footer>
<aside id="cartDrawer" class="drawer"><div class="drawer-head"><h2>Your Cart</h2><button id="closeCart">×</button></div><div id="cartItems" class="cart-items"></div><div class="cart-total"><span>Total</span><strong id="cartTotal">₹0</strong></div><a class="btn primary full" href="checkout.html">CHECKOUT →</a><button id="whatsappOrder" class="btn ghost full">ORDER VIA WHATSAPP ↗</button></aside><div id="overlay" class="overlay"></div><div id="searchPanel" class="search-panel"><button id="closeSearch">×</button><input id="shopSearch" type="search" placeholder="Search the vault…" onkeydown="if(event.key==='Enter')location.href='shop.html?q='+encodeURIComponent(this.value)"></div><script src="catalog.js"></script><script src="script.js"></script></body></html>'''

def cards(items): return '<div class="product-grid">'+''.join([f'<article class="product-card"><a href="product.html?id={p["id"]}" class="product-image-wrap"><img src="{p["image"]}" alt="{p["name"]}"><span class="badge">{p["badge"]}</span></a><div class="product-info"><div class="product-meta"><span>{p["brand"]}</span><span>{p["category"]}</span></div><h3><a href="product.html?id={p["id"]}">{p["name"]}</a></h3><p class="condition">{p["condition"]}</p><div class="product-bottom"><strong>{"Price on request" if p["price"] is None else "₹"+format(p["price"],",")}</strong>{"<button class=\"add\" disabled>SOLD OUT</button>" if p["status"]=="sold" else ("<button class=\"add\" disabled>PRICE ON REQUEST</button>" if p["price"] is None else f'<button class="add" onclick="addToCart(\'{p["id"]}\')">ADD TO CART</button>')}</div></div></article>' for p in items])+'</div>'

pages={}
pages['shop.html']=shell('Shop', '''<section class="page-hero"><p class="eyebrow">THE VAULT</p><h1>Shop the<br><em>collection.</em></h1><p>Browse every current listing by category, brand and collector condition.</p></section><section class="section shop-section"><div class="shop-toolbar"><input id="shopSearch" class="catalog-search" type="search" placeholder="Search products, brands, series…"><div class="filters"><button class="filter active" data-filter="All">All</button><button class="filter" data-filter="Action Figures">Action Figures</button><button class="filter" data-filter="Die-Cast">Die-Cast</button><button class="filter" data-filter="Vintage">Vintage</button><button class="filter" data-filter="Pop Culture">Pop Culture</button></div></div><div id="productGrid" class="product-grid"></div></section>''')
pages['categories.html']=shell('Categories', '''<section class="page-hero"><p class="eyebrow">SHOP BY CATEGORY</p><h1>Choose your<br><em>universe.</em></h1><p>Each category has its own page, catalogue and collector focus.</p></section><section class="section"><div class="category-grid"><a class="category cat-figures" href="action-figures.html"><span>01</span><h3>Action<br>Figures</h3><b>OPEN PAGE →</b></a><a class="category cat-diecast" href="die-cast.html"><span>02</span><h3>Die-Cast<br>& Cars</h3><b>OPEN PAGE →</b></a><a class="category cat-vintage" href="vintage.html"><span>03</span><h3>Vintage<br>Vault</h3><b>OPEN PAGE →</b></a><a class="category cat-pop" href="pop-culture.html"><span>04</span><h3>Pop<br>Culture</h3><b>OPEN PAGE →</b></a></div></section>''')
pages['brands.html']=shell('Brands', '''<section class="page-hero"><p class="eyebrow">SHOP BY BRAND</p><h1>Know the<br><em>maker.</em></h1><p>Go directly to a manufacturer's catalogue and see every NerdVerse India listing under that brand.</p></section><section class="section brand-grid"><a class="brand-tile" href="mattel.html"><span>MATTEL</span><h2>Hot Wheels</h2><p>Premium 1:64 die-cast, Fast & Furious and collector cars.</p><b>VIEW MATTEL →</b></a><a class="brand-tile" href="funskool.html"><span>FUNSKOOL</span><h2>G.I. Joe</h2><p>Vintage Indian-market G.I. Joe International Heroes releases.</p><b>VIEW FUNSKOOL →</b></a></section>''')
pages['rare.html']=shell('Rare Finds', '''<section class="page-hero"><p class="eyebrow">THE RARE VAULT</p><h1>Hard to find.<br><em>Harder to ignore.</em></h1><p>Vintage and collector pieces where packaging condition, scarcity and provenance matter.</p></section><section class="section">{cards}</section>'''.format(cards=cards([])))
# rare should be vintage + all diecast special, populated manually via JS for simplicity
pages['rare.html']=shell('Rare Finds', '''<section class="page-hero"><p class="eyebrow">THE RARE VAULT</p><h1>Hard to find.<br><em>Harder to ignore.</em></h1><p>Vintage releases and collector-grade pieces currently in the NerdVerse India vault.</p></section><section class="section"><div id="rareProducts" class="product-grid"></div></section><script>document.addEventListener('DOMContentLoaded',()=>renderGrid('rareProducts',CATALOG.filter(p=>p.category==='Action Figures'||p.status==='sold')))</script>''')
pages['about.html']=shell('About', '''<section class="page-hero"><p class="eyebrow">OUR PHILOSOPHY</p><h1>Not a toy shop.<br><em>A collector's den.</em></h1><p>NerdVerse India is built around the thrill of the hunt — the hunt for the model, figure or vintage release that makes a collection feel complete.</p></section><section class="section about-long"><div><h2>Collector-first.</h2><p>We want every listing to tell you what matters: manufacturer, series, condition, packaging state and whether the piece is available.</p></div><div><h2>Real listings.</h2><p>The current catalogue is based on actual NerdVerse India product posts and supplied product photography. We do not fill missing prices with guesses.</p></div><div><h2>India focused.</h2><p>Orders are currently handled through WhatsApp while the storefront is being launched. Online payments can be added once the merchant setup is ready.</p></div></section>''')
pages['contact.html']=shell('Contact', '''<section class="page-hero"><p class="eyebrow">GET IN TOUCH</p><h1>Talk to the<br><em>collector's den.</em></h1><p>Have a product question, want to reserve a piece or looking for something specific?</p></section><section class="section contact-grid"><a class="contact-card" href="https://wa.me/917411134696" target="_blank"><span>WHATSAPP</span><h2>+91 74111 34696</h2><p>Fastest way to ask about availability, price or an order.</p><b>MESSAGE →</b></a><a class="contact-card" href="https://www.instagram.com/nerdverseindia/" target="_blank" rel="noopener"><span>INSTAGRAM</span><h2>@nerdverseindia</h2><p>See new drops, product photography and collector updates.</p><b>OPEN INSTAGRAM →</b></a></section>''')

cats={'action-figures.html':('Action Figures','Action Figures','Vintage and modern figures currently listed in the vault.'),'die-cast.html':('Die-Cast & Cars','Die-Cast','Hot Wheels and other 1:64-scale collector vehicles.'),'vintage.html':('Vintage Vault','Action Figures','Older releases and vintage packaging where condition matters.'),'pop-culture.html':('Pop Culture','Pop Culture','Character, gaming and entertainment collectibles.')}
for fn,(title,cat,desc) in cats.items():
    pages[fn]=shell(title,f'''<section class="page-hero"><p class="eyebrow">CATEGORY</p><h1>{title.replace('&','&amp;')}<br><em>collection.</em></h1><p>{desc}</p></section><section class="section"><div id="categoryProducts" class="product-grid"></div></section><script>document.addEventListener('DOMContentLoaded',()=>renderGrid('categoryProducts',CATALOG.filter(p=>p.category==='{cat}')))</script>''')

brands={'mattel.html':('Mattel','Mattel','Hot Wheels Premium die-cast listings.'),'funskool.html':('Funskool','Funskool','Vintage G.I. Joe International Heroes listings.')}
for fn,(title,brand,desc) in brands.items():
    pages[fn]=shell(title,f'''<section class="page-hero"><p class="eyebrow">BRAND</p><h1>{title}<br><em>collection.</em></h1><p>{desc}</p></section><section class="section"><div id="brandProducts" class="product-grid"></div></section><script>document.addEventListener('DOMContentLoaded',()=>renderGrid('brandProducts',CATALOG.filter(p=>p.brand==='{brand}')))</script>''')

pages['product.html']=shell('Product', '''<section class="section product-detail" id="productDetail"></section>''')

for fn,html in pages.items(): (root/fn).write_text(html,encoding='utf-8')
