async function ensureCommerceClient(){if(window.supabase&&window.NV_CONFIG)return;await new Promise(resolve=>{if(window.NV_CONFIG)return resolve();const x=document.createElement('script');x.src='config.js';x.onload=resolve;x.onerror=resolve;document.head.appendChild(x)});if(window.NV_CONFIG&&window.NV_CONFIG.supabaseUrl&&!window.NV_CONFIG.supabaseUrl.includes('YOUR_PROJECT_REF')&&!window.supabase){await new Promise(resolve=>{const x=document.createElement('script');x.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';x.onload=resolve;x.onerror=resolve;document.head.appendChild(x)})}}
let cart=JSON.parse(localStorage.getItem('nv-cart')||'[]');
const cfg={whatsapp:'917411134696',instagram:'https://www.instagram.com/nerdverseindia/'};
function money(n){return n==null?'Price on request':'₹'+Number(n).toLocaleString('en-IN')}
function saveCart(){localStorage.setItem('nv-cart',JSON.stringify(cart));renderCart()}
function addToCart(id){const p=ACTIVE_CATALOG.find(x=>x.id===id);if(!p||p.status==='sold'||p.price==null||Number(p.stock_qty||0)<=0){return}const found=cart.find(x=>x.id===id);if(found)found.qty++;else cart.push({...p,qty:1});saveCart();openCart()}
function removeFromCart(id){cart=cart.filter(x=>x.id!==id);saveCart()}
function renderCart(){const count=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+(x.price||0)*x.qty,0);const c=document.getElementById('cartCount'),t=document.getElementById('cartTotal'),items=document.getElementById('cartItems');if(c)c.textContent=count;if(t)t.textContent=money(total);if(items)items.innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><div><b>${x.name}</b><small>${x.qty} × ${money(x.price)}</small></div><button class="remove" onclick="removeFromCart('${x.id}')">Remove</button></div>`).join(''):`<p style="color:#777">Your cart is empty. The hunt continues.</p>`}
function openCart(){document.getElementById('cartDrawer')?.classList.add('open');document.getElementById('overlay')?.classList.add('show')}
function closeCart(){document.getElementById('cartDrawer')?.classList.remove('open');document.getElementById('overlay')?.classList.remove('show')}
function productCard(p){const disabled=p.status==='sold'||p.price==null||Number(p.stock_qty||0)<=0;return `<article class="product-card"><a href="product.html?id=${encodeURIComponent(p.id)}" class="product-image-wrap"><img src="${p.image}" alt="${p.name}"><span class="badge">${p.badge}</span></a><div class="product-info"><div class="product-meta"><span>${p.brand}</span><span>${p.category}</span></div><h3><a href="product.html?id=${encodeURIComponent(p.id)}">${p.name}</a></h3><p class="condition">${p.condition}</p><div class="product-bottom"><strong>${money(p.price)}</strong>${disabled?`<button class="add" disabled>${p.status==='sold'||Number(p.stock_qty||0)<=0?'SOLD OUT':'PRICE ON REQUEST'}</button>`:`<button class="add" onclick="addToCart('${p.id}')">ADD TO CART</button>`}</div></div></article>`}
function renderGrid(targetId,list){const el=document.getElementById(targetId);if(el)el.innerHTML=list.map(productCard).join('')||'<p class="empty">No pieces found.</p>'}
function setupShop(){const grid=document.getElementById('productGrid');if(!grid)return;let filter=new URLSearchParams(location.search).get('category')||'All';let brand=new URLSearchParams(location.search).get('brand')||'All';let q=new URLSearchParams(location.search).get('q')||'';const segment=new URLSearchParams(location.search).get('segment')||'';const filters=document.querySelectorAll('.filter');function draw(){let list=ACTIVE_CATALOG.filter(p=>(filter==='All'||p.category===filter)&&(brand==='All'||p.brand===brand)&&(!segment||nvDetectSegment(p).toLowerCase()===segment.toLowerCase()||nvNormalize(p.brand)===nvNormalize(segment))&&(!q||`${p.name} ${p.brand} ${p.category} ${p.series}`.toLowerCase().includes(q)));renderGrid('productGrid',list);filters.forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}filters.forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;history.replaceState({},'',`shop.html${filter==='All'?'':`?category=${encodeURIComponent(filter)}`}`);draw()}));const activeSegment=document.getElementById('activeSegment');if(activeSegment&&segment){activeSegment.textContent='Browsing: '+segment;activeSegment.hidden=false;}const search=document.getElementById('shopSearch');search?.addEventListener('input',e=>{q=e.target.value.toLowerCase();draw()});draw()}
function renderProductPage(){const el=document.getElementById('productDetail');if(!el)return;if(!ACTIVE_CATALOG.length){el.textContent='No products published yet. Check back soon.';return;}const p=ACTIVE_CATALOG.find(x=>x.id===new URLSearchParams(location.search).get('id'))||ACTIVE_CATALOG[0];el.innerHTML=`<div class="product-detail-image"><img src="${p.image}" alt="${p.name}"></div><div class="product-detail-copy"><p class="eyebrow">${p.brand.toUpperCase()} · ${p.category.toUpperCase()}</p><h1>${p.name}</h1><div class="detail-price">${money(p.price)}</div><p class="detail-condition">${p.condition}</p><p class="detail-description">${p.description}</p><div class="detail-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><ul class="detail-list">${p.details.map(t=>`<li>${t}</li>`).join('')}</ul><div class="detail-actions">${(p.status==='sold'||Number(p.stock_qty||0)<=0)?'<button class="btn ghost full" disabled>SOLD OUT</button>':p.price==null?`<a class="btn primary full" target="_blank" href="https://wa.me/${cfg.whatsapp}?text=${encodeURIComponent('Hi NerdVerse India, I am interested in '+p.name+'. Please share the current price and availability.')}">ASK ON WHATSAPP</a>`:`<button class="btn primary full" onclick="addToCart('${p.id}')">ADD TO CART · ${money(p.price)}</button><a class="btn ghost full" target="_blank" href="https://wa.me/${cfg.whatsapp}?text=${encodeURIComponent('Hi NerdVerse India, I would like to buy '+p.name+'. Please confirm availability and payment details.')}">BUY VIA WHATSAPP ↗</a>`}</div><p class="micro-note">Shipping is extra unless otherwise stated. DIT/LIT is not covered on listings where specified.</p></div>`;document.title=p.name+' | NerdVerse India'}
function setupCommon(){document.getElementById('cartBtn')?.addEventListener('click',openCart);document.getElementById('closeCart')?.addEventListener('click',closeCart);document.getElementById('overlay')?.addEventListener('click',closeCart);document.getElementById('whatsappOrder')?.addEventListener('click',()=>{if(!cart.length)return alert('Your cart is empty.');const total=cart.reduce((a,x)=>a+(x.price||0)*x.qty,0);const text=`Hi NerdVerse India! I'd like to order:\n${cart.map(x=>`• ${x.name} × ${x.qty} — ${money(x.price*x.qty)}`).join('\n')}\n\nTotal: ${money(total)}\n\nPlease confirm availability and payment details.`;window.open('https://wa.me/'+cfg.whatsapp+'?text='+encodeURIComponent(text),'_blank')});document.getElementById('searchBtn')?.addEventListener('click',()=>document.getElementById('searchPanel')?.classList.add('open'));document.getElementById('closeSearch')?.addEventListener('click',()=>document.getElementById('searchPanel')?.classList.remove('open'));renderCart();setupShop();renderProductPage()}
document.addEventListener('DOMContentLoaded',async()=>{await ensureCommerceClient();await hydrateCatalog();setupCommon();});
